FROM python:3.10-slim

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Install Poetry
ENV POETRY_HOME="/opt/poetry" \
    POETRY_VERSION=1.8.2 \
    POETRY_VIRTUALENVS_CREATE=false \
    POETRY_NO_INTERACTION=1 \
    POETRY_CACHE_DIR="/var/cache/pypoetry"

RUN pip install --no-cache-dir poetry==$POETRY_VERSION

# Copy project files
COPY pyproject.toml poetry.lock* ./

# Install Python packages using Poetry
RUN poetry install --no-interaction --no-root --no-dev

# Set $DAGSTER_HOME and create necessary directories
ENV DAGSTER_HOME=/opt/dagster/dagster_home
RUN mkdir -p $DAGSTER_HOME

# Create necessary directories
RUN mkdir -p /tmp/dagster

# Create directory for dbt project
RUN mkdir -p /opt/dagster/app

WORKDIR $DAGSTER_HOME
